### PR TITLE
Refactor charge

### PR DESCRIPTION
**Pull request by Julianobsg**
Move charges controller and charge container logic to common gem and common frontend package respectively.

Also moved SimpleDialog to avoid code replication and using it in the library would make more sense.

### CODE REVIEW

**Comment by daniel-sim** [comment]
@mib32 Please review but don't merge

**Comment by mib32** [comment]
@Julianobsg What would you do if you wanted to change the price and trial days of the app? And other variable parameters of a charge.

**Comment by Julianobsg** [comment]
Answered that here
https://github.com/pemberton-rank/common/pull/10

I couldn't finish this yesterday, but the idea here is to minimize the exposed params, will add some commits to show you how, just a minute

**Comment by mib32** [comment]
@Julianobsg Got it Julian! Thanks, that looks perfect now. Although, it's interesting why you chose to leave staff plan "terms" without ability to be customised. It is really unlikely to change, I agree, but I personally in favor of more customizability in this context.

**Comment by Julianobsg** [comment]
Good point about that, I thought of doing it but I avoided for 2 reasons.
1. The user can feel bloated with many custom settings, in this case, I do know for sure why the terms are different in this two cases, why we have a term for staff and other for the normal plan, the same can be sad for the name, that could be done something like that:
`"#{Settings.plan_name}  (Free for Shopify staff)"`
That can reduce the user feel of lots of parameters.

2. The context here is refactoring, so all the things that the user can change are marked with the todo tag, not the case of this one. Not sure why wasn't marked with todo, but changing that will get out of a refactor scope and would something like a bug fix or feature, to avoid a context conflict I chose to not change that.

**Comment by mib32** [comment]
@Julianobsg Thanks for the explanation! I reviewed everything and have no other objections.

**Pull request closed without merging**
